## Preprocessing

In [106]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [107]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df2 = application_df.drop(["EIN", "NAME"],1)
application_df2.head()

<ipython-input-107-a83e6684fd32>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  application_df2 = application_df.drop(["EIN", "NAME"],1)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [108]:
# Determine the number of unique values in each column.
unique_val = application_df2.nunique()
unique_val

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [109]:
# Look at APPLICATION_TYPE value counts for binning - the process of reducing the number of unique categorical values in a dataset and making them numeric.
v_count = application_df2['APPLICATION_TYPE'].value_counts()
v_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [110]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(v_count[v_count < 500].index)
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    application_df2['APPLICATION_TYPE'] = application_df2['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df2['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [111]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df2['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [112]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts[classification_counts>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [113]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts < 700].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df2['CLASSIFICATION'] = application_df2['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [114]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies = pd.get_dummies(application_df2)
application_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [115]:
# Split our preprocessed data into our features and target arrays
X = application_dummies.drop('IS_SUCCESSFUL', axis=1).values
y = application_dummies['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 78)

In [116]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [117]:
X_train_scaled.shape

(25724, 44)

## Compile, Train and Evaluate the Model

In [130]:
from keras.callbacks import Callback

# Custom callback to save model weights every five epochs
class SaveModelWeights(Callback):
    def __init__(self, save_interval=5, filepath='model_weights.h5'):
        super(SaveModelWeights, self).__init__()
        self.save_interval = save_interval
        self.filepath = filepath

    def on_epoch_end(self, epoch, logs=None):
        if (epoch + 1) % self.save_interval == 0:
            self.model.save_weights(self.filepath, overwrite=True)
            print(f"Model weights saved at epoch {epoch + 1}.")

# Define the model - no second hidden layer and x2 times the features
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 100
hidden_nodes_layer2 = 50

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, input_dim=number_input_features, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Number of epochs for training
num_epochs = 100

# Create an instance of the custom callback
save_callback = SaveModelWeights(save_interval=5, filepath='model_weights.h5')

# Train the model using the callback
nn.fit(X_train, y_train, epochs=num_epochs, callbacks=[save_callback])

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 47998.0234 - accuracy: 0.4931
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 36521.2422 - accuracy: 0.4882
Epoch 3/100
804/804 [==============================] - 3s 3ms/step - loss: 38767.1953 - accuracy: 0.5019
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 25292.8223 - accuracy: 0.5060
Epoch 5/100
786/804 [============================>.] - ETA: 0s - loss: 15863.2695 - accuracy: 0.5141Model weights saved at epoch 5.
804/804 [==============================] - 2s 2ms/step - loss: 15642.0625 - accuracy: 0.5152
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 20904.8594 - accuracy: 0.5127
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 6708.6240 - accuracy: 0.5079
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 18135.8984 - accuracy: 0.4941
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 2265.3403 - accuracy: 0.5084
Epoch 10/100
801/804 [============================>.] - ETA: 0s - loss: 11480.7881 - accuracy: 0.5076Model weights saved at epoch 10.
804/804 [==============================] - 2s 3ms/step - loss: 11440.8672 - accuracy: 0.5077
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 8339.8076 - accuracy: 0.4970
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 7182.2744 - accuracy: 0.5217
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 1233.2173 - accuracy: 0.5392
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 2428.4375 - accuracy: 0.5026
Epoch 15/100
798/804 [============================>.] - ETA: 0s - loss: 5531.5083 - accuracy: 0.5065Model weights saved at epoch 15.
804/804 [==============================] - 2s 2ms/step - loss: 5492.3105 - accuracy: 0.5067
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 1670.5923 - accuracy: 0.5107
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 430.8631 - accuracy: 0.5112
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 55.4989 - accuracy: 0.5255
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 20/100
785/804 [============================>.] - ETA: 0s - loss: 0.6912 - accuracy: 0.5318Model weights saved at epoch 20.
804/804 [==============================] - 2s 2ms/step - loss: 0.6911 - accuracy: 0.5321
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6911 - accuracy: 0.5321
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 25/100
794/804 [============================>.] - ETA: 0s - loss: 0.6911 - accuracy: 0.5325Model weights saved at epoch 25.
804/804 [==============================] - 2s 3ms/step - loss: 0.6911 - accuracy: 0.5321
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6911 - accuracy: 0.5321
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 30/100
801/804 [============================>.] - ETA: 0s - loss: 0.6912 - accuracy: 0.5322Model weights saved at epoch 30.
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6911 - accuracy: 0.5321
Epoch 35/100
791/804 [============================>.] - ETA: 0s - loss: 0.6912 - accuracy: 0.5321Model weights saved at epoch 35.
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6911 - accuracy: 0.5321
Epoch 40/100
801/804 [============================>.] - ETA: 0s - loss: 0.6912 - accuracy: 0.5325Model weights saved at epoch 40.
804/804 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 45/100
789/804 [============================>.] - ETA: 0s - loss: 0.6912 - accuracy: 0.5330Model weights saved at epoch 45.
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6909 - accuracy: 0.5310
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 50/100
787/804 [============================>.] - ETA: 0s - loss: 0.6911 - accuracy: 0.5329Model weights saved at epoch 50.
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 55/100
787/804 [============================>.] - ETA: 0s - loss: 0.6915 - accuracy: 0.5316Model weights saved at epoch 55.
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 60/100
793/804 [============================>.] - ETA: 0s - loss: 0.6912 - accuracy: 0.5325Model weights saved at epoch 60.
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 65/100
804/804 [==============================] - ETA: 0s - loss: 0.6913 - accuracy: 0.5321Model weights saved at epoch 65.
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 70/100
790/804 [============================>.] - ETA: 0s - loss: 0.6911 - accuracy: 0.5328Model weights saved at epoch 70.
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 75/100
794/804 [============================>.] - ETA: 0s - loss: 0.6913 - accuracy: 0.5323Model weights saved at epoch 75.
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5311
Epoch 80/100
791/804 [============================>.] - ETA: 0s - loss: 0.6913 - accuracy: 0.5321Model weights saved at epoch 80.
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5308
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 85/100
784/804 [============================>.] - ETA: 0s - loss: 0.6912 - accuracy: 0.5322Model weights saved at epoch 85.
804/804 [==============================] - 2s 2ms/step - loss: 0.6912 - accuracy: 0.5321
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5307
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6911 - accuracy: 0.5321
Epoch 90/100
788/804 [============================>.] - ETA: 0s - loss: 0.6915 - accuracy: 0.5317Model weights saved at epoch 90.
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 95/100
782/804 [============================>.] - ETA: 0s - loss: 0.6914 - accuracy: 0.5316Model weights saved at epoch 95.
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6914 - accuracy: 0.5321
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6911 - accuracy: 0.5321
Epoch 100/100
800/804 [============================>.] - ETA: 0s - loss: 0.6913 - accuracy: 0.5320Model weights saved at epoch 100.
804/804 [==============================] - 2s 2ms/step - loss: 0.6913 - accuracy: 0.5321

In [131]:
# Check the structure of the model
nn.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_33 (Dense)            (None, 100)               4500

 dense_34 (Dense)            (None, 50)                5050

 dense_35 (Dense)            (None, 1)                 51

=================================================================
Total params: 9,601
Trainable params: 9,601
Non-trainable params: 0
_________________________________________________________________

In [132]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.9772 - accuracy: 0.5332 - 643ms/epoch - 2ms/step
Loss: 0.9771716594696045, Accuracy: 0.5331778526306152

In [101]:
nn.save("Alphabet_Soup_Charity_3.h5")
print("Evaluation results saved to AlphabetSoupCharity3.h5")

Evaluation results saved to AlphabetSoupCharity3.h5